name: Bug report
description: Create a report to help us improve
title: "[BUG] <title>"
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |

        Please search to see if an issue already exists for the bug you encountered.

        This is a bug report, If you need general support, please visit us on [Discord](https://discord.klipper3d.org/)

        # Guidelines:
        1. Logfile must be provided and not just a little snip, from ks startup up to the bug
        2. The version used must be from this repo (not a fork)
        3. The version used shouldn't be too old (older than the last tagged version)

        This bug report will be closed if the guidelines are not respected.


        #### This is an Open Source project developed voluntarily, there are no Warranties, or ETA.
        [License](https://github.com/KlipperScreen/KlipperScreen/blob/master/LICENSE)

        ### Thank you for choosing KlipperScreen

  - type: textarea
    id: what-happened
    attributes:
      label: 'What happened?'
      description: A clear and concise description of what the bug is.
      placeholder: During a print i pressed pause and nothing happend
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 'What did you expect to happen instead?'
      description: A clear and concise description of what you expected to happen instead.
      placeholder: The printer to pause.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: 'How to reproduce this bug?'
      description: A clear and concise description with precise steps to reproduce this bug.
      placeholder: Press pause button and during printing.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: 'Additional information:'
      description: Any additional info, screenshots or recordings which help to describe the issue.
      placeholder: hardware info or related printer config.
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: |
        Please attach the FULL klipperscreen.log and if needed xorg.log or the tail of journalctl.
        if you need help to find the log file:
        Read the [Documentation](https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/)
      placeholder: |
        #### The LOG file is REQUIRED. Without the logfile your issue will be closed

        Use a Zip archive if needed

      render: shell
    validations:
      required: true
