name: Verify Code Formatting
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'ks_includes/locales/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'ks_includes/locales/**'
jobs:
  lint-python-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install and run Ruff
        uses: astral-sh/ruff-action@v4.0.0
      - run: ruff check --fix screen.py ks_includes ks_includes/widgets panels
      - run: ruff format screen.py ks_includes panels
