name: test-code
on: [push, pull_request]
jobs:
  lint-python-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "screen.py ks_includes panels"
          use-pylint: false
          use-pycodestyle: true
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pycodestyle-options: "--ignore=E402,W503,W504 --max-line-length=120 --max-doc-length=120"
