name: test-code
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'ks_includes/locales/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'ks_includes/locales/**'
jobs:
  lint-python-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff check
        run: ruff check screen.py ks_includes panels
      - name: Run ruff format
        run: ruff format --check screen.py ks_includes panels
